-- MySQL Script generated by MySQL Workbench
-- Mon Oct 24 22:17:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `Nazwa` VARCHAR(256) NOT NULL,
  `Data` VARCHAR(255) NOT NULL,
  `miejsce` VARCHAR(256) NOT NULL,
  `Kontrahent` VARCHAR(256) NOT NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`Pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownicy` (
  `Id_Pracownika` INT(6) NOT NULL,
  `Imie_Pracownika` VARCHAR(45) NOT NULL,
  `Nazwisko_Pracownika` VARCHAR(45) NOT NULL,
  `Oddział` ENUM('Reklama', 'Wykonawczy', 'Ochrona', 'Konserwacja') NOT NULL,
  `Zarobki` SMALLINT(5) NOT NULL,
  PRIMARY KEY (`Id_Pracownika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studebnt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Studebnt` (
  `nrindeksu` SMALLINT(6) NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `adres` VARCHAR(60) NOT NULL,
  `data_ur` DATE NOT NULL,
  `typ_studiow` ENUM('ST', 'NST') NOT NULL,
  `rok_studiow` TINYINT(3) NOT NULL,
  PRIMARY KEY (`nrindeksu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik` (
  `idPracownika` SMALLINT(6) NOT NULL,
  `PESEL` CHAR(11) NOT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Adres` VARCHAR(60) NULL,
  `data_ur` DATE NULL,
  `telefon` VARCHAR(15) NULL,
  `zarobki` FLOAT(7,2) NULL,
  `stanowisko` ENUM('mgr', 'dr', 'prof') NULL,
  `zarobki_dod` INT(10) NULL,
  `kod_pocztowy` CHAR(6) NULL,
  PRIMARY KEY (`idPracownika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Przedmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Przedmiot` (
  `id_przedmiotu` SMALLINT(6) NOT NULL,
  `nazwa_przedmiotu` VARCHAR(45) NOT NULL,
  `idPracownika` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`id_przedmiotu`),
  INDEX `fk_Przedmiot_Pracownik1_idx` (`idPracownika` ASC) VISIBLE,
  CONSTRAINT `fk_Przedmiot_Pracownik1`
    FOREIGN KEY (`idPracownika`)
    REFERENCES `mydb`.`Pracownik` (`idPracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ocena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ocena` (
  `nrindeksu` SMALLINT(6) NULL,
  `id_przedmiotu` SMALLINT(6) NULL,
  `ocena` TINYINT(3) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`nrindeksu`, `id_przedmiotu`),
  INDEX `fk_Studebnt_has_Przedmiot_Przedmiot1_idx` (`id_przedmiotu` ASC) VISIBLE,
  INDEX `fk_Studebnt_has_Przedmiot_Studebnt_idx` (`nrindeksu` ASC) VISIBLE,
  CONSTRAINT `fk_Studebnt_has_Przedmiot_Studebnt`
    FOREIGN KEY (`nrindeksu`)
    REFERENCES `mydb`.`Studebnt` (`nrindeksu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Studebnt_has_Przedmiot_Przedmiot1`
    FOREIGN KEY (`id_przedmiotu`)
    REFERENCES `mydb`.`Przedmiot` (`id_przedmiotu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dostawcy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dostawcy` (
  `Nazwa_Dostawcy` VARCHAR(45) NOT NULL,
  `adres_dostawcy` VARCHAR(45) NOT NULL,
  `tel_dostawcy` INT(15) NOT NULL,
  PRIMARY KEY (`Nazwa_Dostawcy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`odbiorca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`odbiorca` (
  `Nazwa_Odbiorcy` VARCHAR(45) NOT NULL,
  `adres_odbiorcy` VARCHAR(45) NOT NULL,
  `tel_odbiorcy` INT(15) NOT NULL,
  PRIMARY KEY (`Nazwa_Odbiorcy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roczliczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roczliczenia` (
  `nr_rozliczenia` INT(11) NOT NULL,
  `koszt_organizacji` INT NOT NULL,
  `przychod_z_eventu` INT NOT NULL,
  `Nazwa_Dostawcy` VARCHAR(45) NOT NULL,
  `Nazwa_Odbiorcy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nr_rozliczenia`, `Nazwa_Dostawcy`, `Nazwa_Odbiorcy`),
  INDEX `fk_Roczliczenia_dostawcy2_idx` (`Nazwa_Dostawcy` ASC) VISIBLE,
  INDEX `fk_Roczliczenia_odbiorca1_idx` (`Nazwa_Odbiorcy` ASC) VISIBLE,
  CONSTRAINT `fk_Roczliczenia_dostawcy2`
    FOREIGN KEY (`Nazwa_Dostawcy`)
    REFERENCES `mydb`.`dostawcy` (`Nazwa_Dostawcy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roczliczenia_odbiorca1`
    FOREIGN KEY (`Nazwa_Odbiorcy`)
    REFERENCES `mydb`.`odbiorca` (`Nazwa_Odbiorcy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kontrahent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kontrahent` (
  `Nazwa_K` VARCHAR(45) NOT NULL,
  `NIP_K` VARCHAR(45) NOT NULL,
  `Adres` VARCHAR(45) NOT NULL,
  `nr_kontaktowy` VARCHAR(15) NOT NULL,
  `nr_rozliczenia` INT(11) NOT NULL,
  PRIMARY KEY (`Nazwa_K`),
  INDEX `fk_Kontrahent_Roczliczenia1_idx` (`nr_rozliczenia` ASC) VISIBLE,
  CONSTRAINT `fk_Kontrahent_Roczliczenia1`
    FOREIGN KEY (`nr_rozliczenia`)
    REFERENCES `mydb`.`Roczliczenia` (`nr_rozliczenia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownicy` (
  `Id_Pracownika` INT(6) NOT NULL,
  `Imie_Pracownika` VARCHAR(45) NOT NULL,
  `Nazwisko_Pracownika` VARCHAR(45) NOT NULL,
  `Oddział` ENUM('Reklama', 'Wykonawczy', 'Ochrona', 'Konserwacja') NOT NULL,
  `Zarobki` SMALLINT(5) NOT NULL,
  PRIMARY KEY (`Id_Pracownika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EVENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EVENT` (
  `Nazwa_Eventu` VARCHAR(60) NOT NULL,
  `Data_Eventu` DATE NOT NULL,
  `Miejsce_Eventu` VARCHAR(45) NOT NULL,
  `Kontrahent` VARCHAR(45) NOT NULL,
  `odwolany` ENUM('tak', 'nie') NOT NULL,
  `Pracownicy_Id` INT(6) NOT NULL,
  PRIMARY KEY (`Nazwa_Eventu`),
  INDEX `fk_EVENT_Kontrahent1_idx` (`Kontrahent` ASC) VISIBLE,
  INDEX `fk_EVENT_Pracownicy1_idx` (`Pracownicy_Id` ASC) VISIBLE,
  CONSTRAINT `fk_EVENT_Kontrahent1`
    FOREIGN KEY (`Kontrahent`)
    REFERENCES `mydb`.`Kontrahent` (`Nazwa_K`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_Pracownicy1`
    FOREIGN KEY (`Pracownicy_Id`)
    REFERENCES `mydb`.`Pracownicy` (`Id_Pracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
